---

# WARNING: we restart, not reload, nginx, because reload does not verify
# that the new configuration is correct. Note that as long as this is
# the case, server restarts should be performed serially, and multiple
# servers must be used in production environments.

# TODO: find a way to test nginx configuration before copying it into
# place, and reload instead of restarting nginx.

- name: add nginx yum repo
  copy:
    src=nginx.repo
    dest=/etc/yum.repos.d/nginx.repo
    owner=root
    group=root
    mode=0644
  sudo: yes

- name: install nginx
  yum: name=nginx state=present
  sudo: yes
  notify: enable nginx

- name: mkdir /etc/nginx/sites-available
  file:
    path=/etc/nginx/sites-available
    state=directory
    owner=nginx
    group=nginx

- name: mkdir /etc/nginx/sites-enabled
  file:
    path=/etc/nginx/sites-enabled
    state=directory
    owner=nginx
    group=nginx

- name: make {{ wordpress_core_path }}
  file:
    path={{ wordpress_core_path }}
    state=directory

- name: remove default nginx conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  sudo: yes
  notify: restart nginx

- name: remove default ssl nginx conf
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent
  sudo: yes
  notify: restart nginx

- name: install nginx whitelist for internal apps
  template:
    src=allow-whitelist.conf.j2
    dest=/etc/nginx/allow-whitelist.conf
    owner=root
    group=root
    mode=0644
  sudo: yes
  notify: restart nginx

- name: install main nginx configuration file
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
  sudo: yes
  notify: restart nginx

